#!/bin/bash
# Don't run bash scripts unless you know what they do!
# Or run them anyway and it's future you's problem

WORKING_DIR_ABSOLUTE_PATH_VARIABLE_WITH_DETAILED_NAME_SO_PEOPLE_CAN_MORE_EASILY_UNDERSTAND_THE_SCRIPT=$(pwd)

wget https://data.gharchive.org/2021-10-{01..02}-{0..24}.json.gz -P ${WORKING_DIR_ABSOLUTE_PATH_VARIABLE_WITH_DETAILED_NAME_SO_PEOPLE_CAN_MORE_EASILY_UNDERSTAND_THE_SCRIPT}/data/compressed/

mkdir ${WORKING_DIR_ABSOLUTE_PATH_VARIABLE_WITH_DETAILED_NAME_SO_PEOPLE_CAN_MORE_EASILY_UNDERSTAND_THE_SCRIPT}/data/decompressed
cd ${WORKING_DIR_ABSOLUTE_PATH_VARIABLE_WITH_DETAILED_NAME_SO_PEOPLE_CAN_MORE_EASILY_UNDERSTAND_THE_SCRIPT}/data/compressed

for f in *.gz;
do
    gunzip -c "$f" > ${WORKING_DIR_ABSOLUTE_PATH_VARIABLE_WITH_DETAILED_NAME_SO_PEOPLE_CAN_MORE_EASILY_UNDERSTAND_THE_SCRIPT}/data/decompressed/"${f%.*}";
done
